[[HYPRE64]]
arch = "aarch64"
git-tree-sha1 = "7dd7d1fdf13f172eae750f51538cea2ceeef8eb2"
mpi = "mpiabi"
os = "macos"

    [[HYPRE64.download]]
    sha256 = "77c7fffa0105819ff1601141d5eb3b607fb00a40ef66736eb75e612790d5ccac"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE64_jll.jl/releases/download/HYPRE64-v3.1.0+0/HYPRE64.v3.1.0.aarch64-apple-darwin-mpi+mpiabi.tar.gz"
[[HYPRE64]]
arch = "aarch64"
git-tree-sha1 = "019fbb03d4f5a97dfdcb072d5c1a5df186466307"
mpi = "mpich"
os = "macos"

    [[HYPRE64.download]]
    sha256 = "cb46b9c0dd2845124bcaf89b6d5df591c4a779775cf24a47e0c86e5e7675565d"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE64_jll.jl/releases/download/HYPRE64-v3.1.0+0/HYPRE64.v3.1.0.aarch64-apple-darwin-mpi+mpich.tar.gz"
[[HYPRE64]]
arch = "aarch64"
git-tree-sha1 = "3f5c3d6935925f623d1033b613b7d20a63c4904d"
mpi = "mpitrampoline"
os = "macos"

    [[HYPRE64.download]]
    sha256 = "ce643af67d39c94212fa4c6375dc639771b7e6747aefc0b5283e9928458febb4"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE64_jll.jl/releases/download/HYPRE64-v3.1.0+0/HYPRE64.v3.1.0.aarch64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[HYPRE64]]
arch = "aarch64"
git-tree-sha1 = "aea06f835c2f003913976f270975d77637ec23d0"
mpi = "openmpi"
os = "macos"

    [[HYPRE64.download]]
    sha256 = "6d95b36dd14a36ece184120859fedd161099bf22a327ad5e31f1708092929204"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE64_jll.jl/releases/download/HYPRE64-v3.1.0+0/HYPRE64.v3.1.0.aarch64-apple-darwin-mpi+openmpi.tar.gz"
[[HYPRE64]]
arch = "aarch64"
git-tree-sha1 = "4f8315d809bef07c613fe61b327d2c8e35566a47"
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[HYPRE64.download]]
    sha256 = "38d3517822dc84bcdf18772dab1cdcd2fb87b68a15b853122dd171489c2f4d08"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE64_jll.jl/releases/download/HYPRE64-v3.1.0+0/HYPRE64.v3.1.0.aarch64-linux-gnu-mpi+mpiabi.tar.gz"
[[HYPRE64]]
arch = "aarch64"
git-tree-sha1 = "955e83013449b5992ab3902963fb8a4fa3521c72"
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[HYPRE64.download]]
    sha256 = "eb96e5cc586f5819cb07ff100672f9bb508777285131e28e1fa199d556156b6e"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE64_jll.jl/releases/download/HYPRE64-v3.1.0+0/HYPRE64.v3.1.0.aarch64-linux-gnu-mpi+mpich.tar.gz"
[[HYPRE64]]
arch = "aarch64"
git-tree-sha1 = "8a53a58f99348978a1e9e9961ae79705504e1c03"
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[HYPRE64.download]]
    sha256 = "dd1257400f0f412173d9ff0be7ead9ef02507f55546f957309f55048e4ccd91e"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE64_jll.jl/releases/download/HYPRE64-v3.1.0+0/HYPRE64.v3.1.0.aarch64-linux-gnu-mpi+mpitrampoline.tar.gz"
[[HYPRE64]]
arch = "aarch64"
git-tree-sha1 = "abde4a70e65d6e6dc3eb767f4ce556dcff56794c"
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[HYPRE64.download]]
    sha256 = "3150deb97e624fd3e810047c193b2081da59d2eda2985a30d724efcb9278eaf0"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE64_jll.jl/releases/download/HYPRE64-v3.1.0+0/HYPRE64.v3.1.0.aarch64-linux-gnu-mpi+openmpi.tar.gz"
[[HYPRE64]]
arch = "aarch64"
git-tree-sha1 = "bc8f790eca0182db02877c9f8ca9f168376a5ab4"
libc = "musl"
mpi = "mpiabi"
os = "linux"

    [[HYPRE64.download]]
    sha256 = "d754b6bcd5a5b3eb4949e5318f1532d10b091e5da24cbefe0bffe32acf2e3547"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE64_jll.jl/releases/download/HYPRE64-v3.1.0+0/HYPRE64.v3.1.0.aarch64-linux-musl-mpi+mpiabi.tar.gz"
[[HYPRE64]]
arch = "aarch64"
git-tree-sha1 = "e64b7bcd36b96be858780ea7f5cd1ef1a8159905"
libc = "musl"
mpi = "mpich"
os = "linux"

    [[HYPRE64.download]]
    sha256 = "709acc1ef40c531511155e880f5823af430255e031cc9849aec132aa2885576b"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE64_jll.jl/releases/download/HYPRE64-v3.1.0+0/HYPRE64.v3.1.0.aarch64-linux-musl-mpi+mpich.tar.gz"
[[HYPRE64]]
arch = "aarch64"
git-tree-sha1 = "486b596eabe4e9cac55a9af54dbaec18129ace53"
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[HYPRE64.download]]
    sha256 = "33b037ef5edf5fb36b79b2fd2cf2c201e977945e7497904e4aa62420140ccff3"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE64_jll.jl/releases/download/HYPRE64-v3.1.0+0/HYPRE64.v3.1.0.aarch64-linux-musl-mpi+openmpi.tar.gz"
[[HYPRE64]]
arch = "aarch64"
git-tree-sha1 = "9a515b157a5047cedf2122c897088aa9dce09047"
mpi = "mpiabi"
os = "freebsd"

    [[HYPRE64.download]]
    sha256 = "49ecff938d57f147f2bff44b656b2a02485b75ef65e23e5d192de580924bffc2"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE64_jll.jl/releases/download/HYPRE64-v3.1.0+0/HYPRE64.v3.1.0.aarch64-unknown-freebsd-mpi+mpiabi.tar.gz"
[[HYPRE64]]
arch = "aarch64"
git-tree-sha1 = "48adf0751dfa58eb529eefd149b8fbee0eb63596"
mpi = "mpich"
os = "freebsd"

    [[HYPRE64.download]]
    sha256 = "e212f011334ffc74abaa9193d1a9f307e32af52bb5096619997794ec2665d925"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE64_jll.jl/releases/download/HYPRE64-v3.1.0+0/HYPRE64.v3.1.0.aarch64-unknown-freebsd-mpi+mpich.tar.gz"
[[HYPRE64]]
arch = "aarch64"
git-tree-sha1 = "4ee0ff2c06478714913a9e97586901bbf29fabc5"
mpi = "mpitrampoline"
os = "freebsd"

    [[HYPRE64.download]]
    sha256 = "11018414bfcdddc6ad08a23094ef96e1c41ce75dbb92b00950507a02fb5c8d70"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE64_jll.jl/releases/download/HYPRE64-v3.1.0+0/HYPRE64.v3.1.0.aarch64-unknown-freebsd-mpi+mpitrampoline.tar.gz"
[[HYPRE64]]
arch = "aarch64"
git-tree-sha1 = "dfe308a6916d3f4b7236282ba22bc66291291781"
mpi = "openmpi"
os = "freebsd"

    [[HYPRE64.download]]
    sha256 = "32970c073b08d6fe5986b0278c7e5b81b009f67687450cdaa452de996e93d7e8"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE64_jll.jl/releases/download/HYPRE64-v3.1.0+0/HYPRE64.v3.1.0.aarch64-unknown-freebsd-mpi+openmpi.tar.gz"
[[HYPRE64]]
arch = "powerpc64le"
git-tree-sha1 = "3fa84a3b070042814e88615c9007a759e41abe29"
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[HYPRE64.download]]
    sha256 = "3fee66bb7f67b205a1c54f859ff0f4b7687b7e9995fa93c54d3eedb7b22f8547"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE64_jll.jl/releases/download/HYPRE64-v3.1.0+0/HYPRE64.v3.1.0.powerpc64le-linux-gnu-mpi+mpiabi.tar.gz"
[[HYPRE64]]
arch = "powerpc64le"
git-tree-sha1 = "b776c4961b9374ba6ad0ac29578d40be1096315c"
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[HYPRE64.download]]
    sha256 = "75b13dc2a9d432a196cf71146b7faf3260969e081c4ec7ac9a701de64b289d28"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE64_jll.jl/releases/download/HYPRE64-v3.1.0+0/HYPRE64.v3.1.0.powerpc64le-linux-gnu-mpi+mpich.tar.gz"
[[HYPRE64]]
arch = "powerpc64le"
git-tree-sha1 = "3c3bafb50034c1a8e2dad114c5aff2e965fd75c0"
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[HYPRE64.download]]
    sha256 = "ca5b5ec24b5d091ce1b25ad5f807208105c9c2a345f9ca4ef243f1f611e78113"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE64_jll.jl/releases/download/HYPRE64-v3.1.0+0/HYPRE64.v3.1.0.powerpc64le-linux-gnu-mpi+mpitrampoline.tar.gz"
[[HYPRE64]]
arch = "powerpc64le"
git-tree-sha1 = "c536904883feb42d53f4d4f089bc0e8f36e70eb3"
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[HYPRE64.download]]
    sha256 = "8b9439f9f86424178bd7bebed86f5aa29e2d5b355974037bb33d0c8f9a5385bd"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE64_jll.jl/releases/download/HYPRE64-v3.1.0+0/HYPRE64.v3.1.0.powerpc64le-linux-gnu-mpi+openmpi.tar.gz"
[[HYPRE64]]
arch = "riscv64"
git-tree-sha1 = "afb841c01fbe71a1c68f37ee48905ba1499fe13a"
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[HYPRE64.download]]
    sha256 = "d6f06bc71142c293b811b25da9b41a8611624082260d43eb47a3386386da5bfa"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE64_jll.jl/releases/download/HYPRE64-v3.1.0+0/HYPRE64.v3.1.0.riscv64-linux-gnu-mpi+mpiabi.tar.gz"
[[HYPRE64]]
arch = "riscv64"
git-tree-sha1 = "fe055180e568a19b1beac4b475551a9b4283d37a"
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[HYPRE64.download]]
    sha256 = "0ad60d41d647d808d77dca8fc5d943f2179894deb9046b606cc284a8d3bcc1c6"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE64_jll.jl/releases/download/HYPRE64-v3.1.0+0/HYPRE64.v3.1.0.riscv64-linux-gnu-mpi+mpich.tar.gz"
[[HYPRE64]]
arch = "riscv64"
git-tree-sha1 = "1777e9f2ab4ce832626b61cd371acc50c0bb90ea"
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[HYPRE64.download]]
    sha256 = "e3293fb1734db77471a332af0a6e29a0d7a07e8c1e0fb119694f3a70f462a98f"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE64_jll.jl/releases/download/HYPRE64-v3.1.0+0/HYPRE64.v3.1.0.riscv64-linux-gnu-mpi+mpitrampoline.tar.gz"
[[HYPRE64]]
arch = "riscv64"
git-tree-sha1 = "5cde24d7815e071606010d242767792f7f76a589"
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[HYPRE64.download]]
    sha256 = "139be32f3c626ccca33878e63f46e70f5d8681eea3860f9bca3f9157db8919c3"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE64_jll.jl/releases/download/HYPRE64-v3.1.0+0/HYPRE64.v3.1.0.riscv64-linux-gnu-mpi+openmpi.tar.gz"
[[HYPRE64]]
arch = "x86_64"
git-tree-sha1 = "af99c30ccb73547c142bcc4ffd783a82639a1d3b"
mpi = "mpiabi"
os = "macos"

    [[HYPRE64.download]]
    sha256 = "3a7ccc9f29bb64fad31c75f52982dc3205097575377a23920b83c80b2c3a35e7"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE64_jll.jl/releases/download/HYPRE64-v3.1.0+0/HYPRE64.v3.1.0.x86_64-apple-darwin-mpi+mpiabi.tar.gz"
[[HYPRE64]]
arch = "x86_64"
git-tree-sha1 = "d47af3880f60926c2d70eacf89b91e0ca2cbf009"
mpi = "mpich"
os = "macos"

    [[HYPRE64.download]]
    sha256 = "cd0f764e864e0f3e386d058a7d35bb73ef718d2111125243f3d358909f8b1aad"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE64_jll.jl/releases/download/HYPRE64-v3.1.0+0/HYPRE64.v3.1.0.x86_64-apple-darwin-mpi+mpich.tar.gz"
[[HYPRE64]]
arch = "x86_64"
git-tree-sha1 = "a06d3e115d8b115ad20d648d2c631002e7fee9b6"
mpi = "mpitrampoline"
os = "macos"

    [[HYPRE64.download]]
    sha256 = "22ec49d29d7d35339f8549fe9d9493b4ee17971c368b9696055c7cbfc74244a1"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE64_jll.jl/releases/download/HYPRE64-v3.1.0+0/HYPRE64.v3.1.0.x86_64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[HYPRE64]]
arch = "x86_64"
git-tree-sha1 = "1b71e3c02da506dd47429cff401de23380b52993"
mpi = "openmpi"
os = "macos"

    [[HYPRE64.download]]
    sha256 = "14abd864f1dc4928bdeca6c090de84b884998cd1747f107c011d1116653cfceb"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE64_jll.jl/releases/download/HYPRE64-v3.1.0+0/HYPRE64.v3.1.0.x86_64-apple-darwin-mpi+openmpi.tar.gz"
[[HYPRE64]]
arch = "x86_64"
git-tree-sha1 = "f9fee974b61698d5dc5fa67cec9d148c0ca68ad7"
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[HYPRE64.download]]
    sha256 = "1802654cb7a7d1934de644191f19264136a211bccc5bea4a7072cc49c268dea3"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE64_jll.jl/releases/download/HYPRE64-v3.1.0+0/HYPRE64.v3.1.0.x86_64-linux-gnu-mpi+mpiabi.tar.gz"
[[HYPRE64]]
arch = "x86_64"
git-tree-sha1 = "c4263bf280c14be952284953fda8c85f97e56af7"
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[HYPRE64.download]]
    sha256 = "11a962f15a2f5604f4da351e81fc815e9641636a98f44c31b768f85f2c0f0d1d"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE64_jll.jl/releases/download/HYPRE64-v3.1.0+0/HYPRE64.v3.1.0.x86_64-linux-gnu-mpi+mpich.tar.gz"
[[HYPRE64]]
arch = "x86_64"
git-tree-sha1 = "0ef1e12ec604aa0ee3f1744084df26bc0946ab5e"
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[HYPRE64.download]]
    sha256 = "8730b4fa1db7334bd5310a0f88ff389d91620e874b3e0497ed128c9b07829547"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE64_jll.jl/releases/download/HYPRE64-v3.1.0+0/HYPRE64.v3.1.0.x86_64-linux-gnu-mpi+mpitrampoline.tar.gz"
[[HYPRE64]]
arch = "x86_64"
git-tree-sha1 = "918d3e49180708de1d354e1a45dacbcc074ed3c2"
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[HYPRE64.download]]
    sha256 = "c5399f51d1c7f111a779b1c5770010475101e48bbe6d2ffc73f60ad5f13b7e6b"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE64_jll.jl/releases/download/HYPRE64-v3.1.0+0/HYPRE64.v3.1.0.x86_64-linux-gnu-mpi+openmpi.tar.gz"
[[HYPRE64]]
arch = "x86_64"
git-tree-sha1 = "1c4ff8dbd87687edd354ed995551a9adf487a8d2"
libc = "musl"
mpi = "mpiabi"
os = "linux"

    [[HYPRE64.download]]
    sha256 = "30f6da255aa294b32538d49571de0b8a64dae96f3d5532e06471e34c72e0a5da"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE64_jll.jl/releases/download/HYPRE64-v3.1.0+0/HYPRE64.v3.1.0.x86_64-linux-musl-mpi+mpiabi.tar.gz"
[[HYPRE64]]
arch = "x86_64"
git-tree-sha1 = "9c6db4f33ba1ec067a8ce2018e3319ebca9a037c"
libc = "musl"
mpi = "mpich"
os = "linux"

    [[HYPRE64.download]]
    sha256 = "c8105453ac7f34a9e4ede846c3d1ad68c6783f8cb17497e6bb71209c6f0f8ef1"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE64_jll.jl/releases/download/HYPRE64-v3.1.0+0/HYPRE64.v3.1.0.x86_64-linux-musl-mpi+mpich.tar.gz"
[[HYPRE64]]
arch = "x86_64"
git-tree-sha1 = "fc19eb8262146355075c52131e21f5298385e2a2"
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[HYPRE64.download]]
    sha256 = "3b4f0e3e6a4ff7d84d540c01347d65e8dc704319f580655d6d22a94df3da7bfb"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE64_jll.jl/releases/download/HYPRE64-v3.1.0+0/HYPRE64.v3.1.0.x86_64-linux-musl-mpi+openmpi.tar.gz"
[[HYPRE64]]
arch = "x86_64"
git-tree-sha1 = "380a701f8896fcfab2c5c4d9bab24b252ac0ef4a"
mpi = "mpiabi"
os = "freebsd"

    [[HYPRE64.download]]
    sha256 = "5431681185f95115a9b613ae1022b12e55d68f23950249cb4191a8bd2bc8915e"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE64_jll.jl/releases/download/HYPRE64-v3.1.0+0/HYPRE64.v3.1.0.x86_64-unknown-freebsd-mpi+mpiabi.tar.gz"
[[HYPRE64]]
arch = "x86_64"
git-tree-sha1 = "2e7044fc126b60c61e39e0d5fe72fcc05430b73a"
mpi = "mpich"
os = "freebsd"

    [[HYPRE64.download]]
    sha256 = "50f33fcee032083f07d6212e010deffa372786957ea2f76895cef798fe7f40de"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE64_jll.jl/releases/download/HYPRE64-v3.1.0+0/HYPRE64.v3.1.0.x86_64-unknown-freebsd-mpi+mpich.tar.gz"
[[HYPRE64]]
arch = "x86_64"
git-tree-sha1 = "f152096bbad31af5287ab897256df5aa17880523"
mpi = "mpitrampoline"
os = "freebsd"

    [[HYPRE64.download]]
    sha256 = "b896878fe6660f8bbfc75df71d6125443255ed623b32eaf4a9d66532cd02edca"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE64_jll.jl/releases/download/HYPRE64-v3.1.0+0/HYPRE64.v3.1.0.x86_64-unknown-freebsd-mpi+mpitrampoline.tar.gz"
[[HYPRE64]]
arch = "x86_64"
git-tree-sha1 = "fc2849f837939658d26e7c0e4118f97859e8b527"
mpi = "openmpi"
os = "freebsd"

    [[HYPRE64.download]]
    sha256 = "64ce0a3ab8619dfdfbad9048b467a8373c36c00c9aa2025d9d8fe302bd4eb477"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE64_jll.jl/releases/download/HYPRE64-v3.1.0+0/HYPRE64.v3.1.0.x86_64-unknown-freebsd-mpi+openmpi.tar.gz"
[[HYPRE64]]
arch = "x86_64"
git-tree-sha1 = "71be2b8a330fe7eb59600c809fd82b380a5e552f"
mpi = "microsoftmpi"
os = "windows"

    [[HYPRE64.download]]
    sha256 = "de330b416ba670694d04736a7948c71d7ca5d544e943135059a2c58243019643"
    url = "https://github.com/JuliaBinaryWrappers/HYPRE64_jll.jl/releases/download/HYPRE64-v3.1.0+0/HYPRE64.v3.1.0.x86_64-w64-mingw32-mpi+microsoftmpi.tar.gz"
