# Autogenerated wrapper script for HYPRE64_jll for x86_64-linux-musl-mpi+mpich
export libHYPRE64

using libblastrampoline_jll
using CompilerSupportLibraries_jll
using MPICH_jll
JLLWrappers.@generate_wrapper_header("HYPRE64")
JLLWrappers.@declare_library_product(libHYPRE64, "libHYPRE64.so.301")
function __init__()
    JLLWrappers.@generate_init_header(libblastrampoline_jll, CompilerSupportLibraries_jll, MPICH_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libHYPRE64,
        "lib/libHYPRE64.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
