# Autogenerated wrapper script for HYPRE64_jll for x86_64-unknown-freebsd-mpi+mpich
export libHYPRE

using libblastrampoline_jll
using LLVMOpenMP_jll
using MPICH_jll
JLLWrappers.@generate_wrapper_header("HYPRE64")
JLLWrappers.@declare_library_product(libHYPRE, "libHYPRE64.so.301")
function __init__()
    JLLWrappers.@generate_init_header(libblastrampoline_jll, LLVMOpenMP_jll, MPICH_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libHYPRE,
        "lib/libHYPRE64.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
