# Autogenerated wrapper script for HYPRE64_jll for x86_64-w64-mingw32-mpi+microsoftmpi
export libHYPRE64

using libblastrampoline_jll
using CompilerSupportLibraries_jll
using MicrosoftMPI_jll
JLLWrappers.@generate_wrapper_header("HYPRE64")
JLLWrappers.@declare_library_product(libHYPRE64, "libHYPRE64.dll")
function __init__()
    JLLWrappers.@generate_init_header(libblastrampoline_jll, CompilerSupportLibraries_jll, MicrosoftMPI_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libHYPRE64,
        "bin\\libHYPRE64.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
